### ISSUE TITLE
GCP Provider error startup-script: Must not run with sudo

### ISSUE THREAD

**Issue by Hdom** [cloudbase/garm-provider-gcp#10]
Hello, running into an error trying to spin up a linux runner in GCP using the garm_provider_gcp.

```
Feb 29 16:12:57 debian google_metadata_script_runner[903]: startup-script: Must not run with sudo
Feb 29 16:13:02 debian google_metadata_script_runner[903]: startup-script: Must not run with sudo
```

Any idea of what I am doing wrong? 

I was thinking of some workarounds: 
1. I can add `export RUNNER_ALLOW_RUNASROOT="1"` as outlined on https://serverfault.com/questions/1052695/must-not-run-with-sudo-while-trying-to-create-a-runner-using-github-actions but this is not ideal.
2. Switch to runner user `sudo su runner` in the additionalCommands section of the ComposeUserData at https://github.com/cloudbase/garm-provider-gcp/blob/main/internal/spec/spec.go#L215. 

Some details (ill update this if I think of any additional details):
- I am using a snapshot created from `projects/debian-cloud/global/images/family/debian-11`

**Comment by Hdom** [comment]
Update on workarounds, I tried workaround 2, but no matter what I try the script runner never switches the user to runner. 

I added `"sudo su " + defaults.DefaultUser + " -s /bin/bash",` to https://github.com/Hdom/garm-provider-gcp/blob/587bc6ad1f3b7d70d35aec8720504aebd84267e6/internal/spec/spec.go#L218 and it still remains on root
```
Feb 29 19:11:39 debian google_metadata_script_runner[904]: startup-script: + sudo su runner -s /bin/bash
Feb 29 19:11:39 debian systemd[1]: Created slice User Slice of UID 1001.
Feb 29 19:11:39 debian systemd[1]: Starting User Runtime Directory /run/user/1001...
Feb 29 19:11:39 debian systemd[1]: Finished User Runtime Directory /run/user/1001.
Feb 29 19:11:39 debian systemd[1]: Starting User Manager for UID 1001...
Feb 29 19:11:39 debian systemd[1]: Started User Manager for UID 1001.
Feb 29 19:11:39 debian systemd[1]: Started Session c1 of user runner.
Feb 29 19:11:39 debian google_metadata_script_runner[904]: startup-script: + whoami
Feb 29 19:11:39 debian systemd[1]: session-c1.scope: Succeeded.
Feb 29 19:11:39 debian google_metadata_script_runner[904]: startup-script: root
```

Looks like the only solution will be to allow run as root, I believe the service installation found here https://github.com/cloudbase/garm-provider-common/blob/main/cloudconfig/templates.go#L205 will run the service as runner so it doesnt matter that it gets configured by root?

**Comment by Hdom** [comment]
Update 2, I tried workaround 1 and it is working runner is up and running, let me know if I should PR this https://github.com/Hdom/garm-provider-gcp/blob/3cccca8567c8c2ae1a2a2c2c775cdb9ebe28fd6a/internal/spec/spec.go#L217

```
Feb 29 19:42:44 debian google_metadata_script_runner[895]: startup-script: + sudo ./svc.sh install runner
Feb 29 19:42:44 debian google_metadata_script_runner[895]: startup-script: Creating launch runner in /etc/systemd/system/actions.runner.Org.gd4vlns-iWRMx5FvnR6O.service
Feb 29 19:42:44 debian google_metadata_script_runner[895]: startup-script: Run as user: runner
Feb 29 19:42:44 debian google_metadata_script_runner[895]: startup-script: Run as uid: 1001
Feb 29 19:42:44 debian google_metadata_script_runner[895]: startup-script: gid: 1002
```

**Comment by gabriel-samfira** [comment]
Hi @Hdom,

It's been a crazy week and I'm now just catching up. So this seems to happen during the setup phase of the runner from what I understand, and it has to do with the fact that we're not properly switching user.

I remember fixing something similar in other cloud-init based systems. GCP seems to not use cloud-init, so that fix is probably needed here as well.

Here is the "fix":

https://github.com/cloudbase/garm-provider-common/blob/bbe4930a1ebf0ed51e86fa00ecd0fcaca6a8bc4a/cloudconfig/util.go#L163

What this does is it creates a script with everything in `/installRunner.sh`, then it runs it all using a login shell. The user must have passwordless sudo enabled. Thus way we don't need to wory about each individual command.

So we need to write the contents of the setup script that comes from garm-provider-common to a file, and use the existing `additionalCommands` as a wrapper that creates a new user with passwordless sudo and executes that script using:

```bash
su -l -c /install_runner.sh runner
```

**Comment by gabriel-samfira** [comment]
@fabi200123 could you have a look?

**Comment by fabi200123** [comment]
@Hdom Can you try the fix and let me know if that solves your issue? I tried to reproduce your error, but without any luck. The `projects/debian-cloud/global/images/family/debian-11` image works fine for me.

**Comment by gabriel-samfira** [comment]
@Hdom feel free to reopen this issue if the problem persists with the patch from #11
